### ISSUE TITLE
Sliders : works well on the app, not on the remote. 

### ISSUE THREAD

**Issue by yoctopuce** [NEEOInc/neeo-sdk#175] opened 2019-01-05 09:37 UTC
I just implemented a slider. It works reasonably well on the NEEO app,   but it is barely usable on the remote

1. Much like closed bug #62 , when changed from an other device, position is not updated on the remote (but position is updated on the app when changed from the remote)
2. When range is large (-1000..1000) the slider is almost unusable on the remote: the slider barely respond to touch, only both extreme values seem accessible, it's likely impossible to select intermediary values.

**Comment by pfiaux** [comment] 2019-01-07 12:55
Thanks for reporting, I'm looking into this as well as some related slider issues.

If you can share some info about your device it might help me to reproduce the issue and narrow down the source:
* Can you share what device type are you using? accessory or light?
* Have you tried to use a different range? like 0-100 or 0-200? if so does that work better?
* Are you using multiple sliders or only 1 on that device?

**Comment by yoctopuce** [comment] 2019-01-07 13:33
I'm working on an ACCESSORY driver for some Yoctopuce products, the -1000...1000 range is typical of a Yocto-servo, I can share the code if you are interested,  Yes it works much better with a 0..100 range. I haven't tested it with several sliders, yet.

**Comment by pfiaux** [comment] 2019-01-07 15:08
Alright, I'm also seeing some issues with a range higher than 1k, I didn't test negative numbers yet but I created an issue internally to track it, once we have a fix we'll include it in the firmware.

As a workaround in the meanwhile, while it's not ideal, you could use 0 to 100 and a mapping internally to the driver translating back to -1000 to 1000. (the screen has a width of 480 pixels, so minus the margins it's still far below a 2000 steps granularity wise)

**Comment by pfiaux** [comment] 2019-01-16 09:52
I've narrowed down the issue with the range to negative ranges, so using 0-2000 should also work.

There's also a second issue with ACCESSORY that I will take a look at, they will not get push updates on the remote, one work around for this is to use LIGHT as a type instead for now.

**Comment by pfiaux** [comment] 2019-01-18 09:23
We have fixes for both issue and they will be included in an upcoming firmware release. I'm closing this since no changes are required on the SDK itself.

Workarounds available on older versions:
- Use positive only sliders (offset the range and translate in SDK driver)
- Use LIGHT as type

**Closed by pfiaux** 2019-01-18 09:23 UTC
Labels: scope : Components, status : in progress, type : bug
