### ISSUE TITLE
Listview images are not scaled correctly on EUI.

### ISSUE THREAD

**Issue by nklerk** [NEEOInc/neeo-sdk#86] opened 2018-05-29 15:30 UTC
When using the App, images in the listview that are larger in height than in width (Scale 3:4) like movie posters/covers are being stretched in a 1:1 (Square) scale. Images with a larger width then their height (like 16:9) or square images 1:1 are displayed like expected.

**Comment by nklerk** [comment] 2018-05-29 15:34
example https://www.youtube.com/watch?v=LQV6Wi-5-CE

**Comment by pfiaux** [comment] 2018-05-30 07:44
Oh nice catch sadly similarly to #85 it looks like the problem is on the Brain firmware side and not the SDK.
I've filed a bug report for the firmware, since the fix wont be on the SDK side I'm closing this.

**Closed by pfiaux** 2018-05-30 07:44 UTC
Labels: scope Components, status : backlog, type : bug
