### ISSUE TITLE
Title and Fishy error

### ISSUE THREAD

**Issue by tmrobert8** [NEEOInc/neeo-sdk#146] opened 2018-11-01 17:04 UTC
While working on the Kaleidescape driver, I named a text label 'title' (by accident actually - should have been 'movieTitle') like...
`moviePlayer.addTextLabel({ name: 'title', label: 'Title'}, (deviceId) => controller.getMovieTitle(deviceId));`

After I added it into the brain, when I clicked on the device - it would startup but when it went to draw the UI - I'd get:
![image](https://user-images.githubusercontent.com/20641634/47866916-73c79680-ddd6-11e8-8e9b-09e621fd663a.png)

When I changed the name from 'title' to 'movieTitle' - it suddenly started working again.

Not sure if this is a bug or there are certain 'reserved' words that should not be used (then the SDK should be rejecting them at the start - so probably still a bug).

**Comment by MichaelKohler** [comment] 2018-11-02 09:02
Hi Tim

Could you reproduce the problem with the SDK MusicPlayer Example? I've tried and couldn't. What I noticed though is that we should do a better job validating the required sensors, switches, sliders, etc. I've removed the title sensor in the SDK example and added a TextLabel with the "title" name. While this lead to an error, it was not the error you describe here.

Could you please send your current status of the code to michael.kohler@neeo.com? Then I can see if there is another problem we need to take care of.

Please also note the following:

>  The player widget requires a lot of different components:
>  - Switches
>    - MUTE (including MUTE_SENSOR)
>    - PLAYING (including PLAYING_SENSOR)
>    - REPEAT (including REPEAT_SENSOR)
>    - SHUFFLE (including SHUFFLE_SENSOR)
>  - Sliders
>    - VOLUME (including VOLUME_SENSOR)
>  - Sensors (read only)
>    - COVER_ART_SENSOR
>    - TITLE_SENSOR
>    - DESCRIPTION_SENSOR
>  - Directories
>    - A root directory
>
> Optionally you can add:
>  - A queue directory
>
> In addition the following buttons are also used:
> - PLAY
> - PLAY TOGGLE
> - PAUSE
> - VOLUME UP
> - VOLUME DOWN
> - MUTE TOGGLE
> - NEXT TRACK
> - PREVIOUS TRACK
> - SHUFFLE TOGGLE
> - REPEAT TOGGLE
> - CLEAR QUEUE

Thanks
Michael

**Comment by tmrobert8** [comment] 2018-11-02 09:06
Not home right now but I believe you reproduced it since I’m using the mediaplayer type when I recreated this one (not musicplayer)

**Comment by MichaelKohler** [comment] 2018-11-07 12:39
I'm marking this as duplicate of https://github.com/NEEOInc/neeo-sdk/issues/156 then.

**Closed by MichaelKohler** 2018-11-07 12:39 UTC
Labels: scope : Components : Player, status : in progress, type : bug
